name: authenticator
description: "An authenticator app that is available on all platforms"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  auto_route: ^8.2.0
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  dio_cookie_manager: ^3.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0 # TODO: make the ios config changes after running flutter build ios
  flutter_bloc: ^8.1.6
  get_it: ^8.0.0-pre-5
  google_fonts: ^6.2.1
  hive: 4.0.0-dev.2
  isar_flutter_libs: 4.0.0-dev.14
  json: ^0.20.2
  otp: ^3.1.4
  path_provider: ^2.1.3

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
